title: Restaurant Customer Satisfaction
description: Machine Learning Project on Restaurant Customer Satisfaction
show_downloads: true
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme 
